[package]
name = "chrono_learn"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = {"version" = "0.4.42", "features" = ["serde"]}
anyhow = "1.0.100"
regex = "1.11.2"
serde = "1.0.225"
serde_json = "1.0.145"
thiserror = "2.0.16"

